# Generated by Django 4.1.7 on 2023-06-23 12:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_profilereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('skills', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, choices=[('full_time', 'full_time'), ('part_time', 'part_time'), ('other', 'other')], max_length=15, null=True)),
                ('education', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('salary', models.PositiveIntegerField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.idea')),
            ],
        ),
    ]
